# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       # 1 将代码仓库的内容拉取（或称为检出）到工作目录中，以便在下面的工作流程中使用
#       - name: Checkout code (检出代码)
#         uses: actions/checkout@v3
#       # 2 安装 node 环境，并设置版本为 16
#       - name: Setup Node.js (设置 node 版本)
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       # 3 安装 pnpm
#       - name: Install pnpm (安装 pnpm)
#         uses: pnpm/action-setup@v2
#         with:
#           version: 7.0.0
#       # 4 安装依赖
#       - name: Install dependencies (安装依赖)
#         run: pnpm install

#       # 5 代码检查，无该命令所以不执行
#       # - name: lint (代码检查)
#       #   run: pnpm run lint

#       # 6 跑测试，无该命令所以不执行
#       # - name: Test (测试)
#       #   run: pnpm run test

#       # 7 构建项目
#       - name: Build (构建)
#         run: pnpm run docs:build
#       # 8
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: docs/.vitepress/dist
name: 部署VitePress

on:
  push:
    branches:
      - main # 这段是在推送到 main 分支时触发该命令

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main # 这一步检查 docs 代码

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0" # 设置 nodejs 的版本

      - name: Install pnpm
        run: npm install -g pnpm # 全局安装 pnpm

      - name: Install dependencies
        run: pnpm install # 使用 pnpm 安装依赖

      - name: Build VitePress
        run: pnpm run docs:build # 这里是打包 vitepress 命令

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }} # 这一步很重要，单独看下面的大步骤，主要是用来给该脚本一些仓库权限
          publish_dir: .vitepress/dist # 指定该文件夹中的 dist
          publish_branch: gh-pages # 推送到关联仓库的 gh-pages 分支
          dotfiles: true # 包括在提交中，即使被 .gitignore 文件忽略
